# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Showcase
email: monkpuah123@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Nothing much so far
baseurl: "" # the subpath of your site, e.g. /blog
url: "boontat.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github: https://github.com/boontat

display_footer: initial  #change this to 'none' if you want to hide the footer copyright text

theme: jekyll-material-theme

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

# Settings for the porfolio section

portfolio_heading: Portfolio
portfolio_type: cards #cards or carousel

project_one: "First Project"
project_one_description: Describe your project!
project_one_url:
project_one_icon: location_on # these are from materiailize css, the full collection is here: http://materializecss.com/icons.html

project_two: Second Project
project_two_description: Describe your project!
project_two_url:
project_two_icon: photo_camera

project_three: Third Project
project_three_description: Describe your project!
project_three_url:
project_three_icon: hotel

project_four: Fourth Project
project_four_description: Describe your project!
project_four_url:
project_four_icon: restaurant

# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: apache
  - name: backbonejs
  - name: bitbucket
  - name: bootstrap
  - name: bower
  - name: codeigniter
  - name: docker
  - name: git
  - name: github
  - name: gitlab
  - name: grunt
  - name: html
  - name: javascript
  - name: laravel
  - name: linux
  - name: mocha
  - name: mysql
  - name: nginx
  - name: nodejs
  - name: php
  - name: python
  - name: ruby
  - name: ssh
  - name: ubuntu
  - name: vim
  - name: vagrant
    uri: https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Vagrant.png/150px-Vagrant.png

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

syntax_highlighting: true # include the css for syntax highlighting

cookie_accept_message: Thanks! # The pop-up dialog that appears after accepting the cookie notice.

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
