# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: About Me
email: monkpuah123@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I don't have good algorithm skill, but i like to use programming to solve problem.
  I like to automate workflow, i think workflow that required many steps should be blackboxed and document down for future reference.
  Only should remember one liner.
baseurl: "" # the subpath of your site, e.g. /blog
url: "boontat.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github: https://github.com/boontat

display_footer: none  #change this to 'none' if you want to hide the footer copyright text

# theme: jekyll-material-theme

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

# Settings for the porfolio section

portfolio_heading: Projects
portfolio_type: cards #cards or carousel

project_one: With PHP
project_one_description: -
project_one_url: -
project_one_icon: location_on # these are from materiailize css, the full collection is here: http://materializecss.com/icons.html

project_two: With Node
project_two_description: Describe your project!
project_two_url:
project_two_icon: photo_camera

# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: bootstrap
  - name: codeigniter
  - name: laravel
  - name: expressjs
  - name: html
  - name: javascript
  - name: css
  - name: nodejs
  - name: php
  - name: git
  - name: mysql
  - name: nginx
  - name: ubuntu
  - name: centos
  - name: vim
  - name: bash
    uri: https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Gnu-bash-logo.svg/216px-Gnu-bash-logo.svg.png
  - name: vagrant
    uri: https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Vagrant.png/150px-Vagrant.png
  - name: docker

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

syntax_highlighting: true # include the css for syntax highlighting

cookie_accept_message: Thanks! # The pop-up dialog that appears after accepting the cookie notice.

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
